disabled_rules:
- conditional_returns_on_newline
- cyclomatic_complexity
- discouraged_object_literal
- explicit_acl
- explicit_enum_raw_value
- explicit_top_level_acl
- explicit_type_interface
- extension_access_modifier
- fallthrough
- file_header
- file_length
- function_body_length
- function_parameter_count
- identifier_name
- implicit_return
- large_tuple
- leading_whitespace
- let_var_whitespace
- line_length
- multiline_arguments
- nimble_operator
- no_extension_access_modifier
- no_grouping_extension
- notification_center_detachment
- number_separator
- object_literal
- override_in_extension
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- required_enum_case
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- trailing_whitespace
- type_body_length
- type_name
- unneeded_parentheses_in_closure_argument

opt_in_rules:
- attributes
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- contains_over_first_not_nil
- control_statement
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_optional_boolean
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- fatal_error_message
- first_where
- force_cast
- force_try
- force_unwrapping
- generic_type_name
- implicit_getter
- implicitly_unwrapped_optional
- is_disjoint
- joined_default_parameter
- legacy_cggeometry_functions
- legacy_constructor
- legacy_nsgeometry_functions
- literal_expression_end_indentation
- mark
- multiline_parameters
- multiple_closures_with_trailing_closure
- nesting
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- sorted_imports
- statement_position
- switch_case_alignment
- syntactic_sugar
- todo
- trailing_comma
- trailing_newline
- trailing_semicolon
- unneeded_break_in_switch
- unused_closure_parameter
- unused_enumerated
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- void_return
- weak_delegate
- xctfail_message
- yoda_condition

excluded:
- Pods
